### ISSUE TITLE
size of app

### ISSUE THREAD

**Issue by Szymono** [RoderickQiu/wnr#51]
My app size is about 250MB. My question is, can u make light version of the app or optimize update?
I use the app on Win10.
![obraz](https://user-images.githubusercontent.com/38432554/135854436-684b17d8-1c3d-4833-be17-2733708eacaa.png)

**Comment by NKID00** [comment]
There may not be any eazy way of making the app smaller. wnr will always have a large copy of Chromium because electron(the framework used by wnr) uses it to render the ui. See [this issue](https://github.com/electron/electron/issues/2003) for more details. Still, the app can be shrunken by cleaning out unnecessary dependencies(which seems to be difficult). 

Is it possible to fork wnr into a more lightweight version with less functionality? @RoderickQiu

**Comment by RoderickQiu** [comment]
Sorry for the delay that I missed this issue.
Frankly speaking, it is not possible to make that kind of an app, as we use Electron framework to program. As NKID says, the package could be optimised, but it won't be more than 5mb so I'm not really interested in it. 
The only way will be to have a online version but I'm sure you can find an alternative in that case, if you only need a simple timing app.
