### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by KEALHOVIK** [RoderickQiu/wnr#54]
Hello, out of everything i tried this time tracker is the closest thing to what i need, thanks!!!
But i have a couple of comments and suggestions to make it a bit more universal and useful.
In terms of comments: I'd say that having a notification sound + interface change + additional window with a message is too annoying. I think the option to just live a simple windows notification + interface change would be ideal.
With suggestions i'll add that it'll be great to have an option to see statistics to separate tasks, not only combined (i'd like to track how much i read vs how much i code vs how much i research). Another feature that would be great is ability to set arbitrary timer without any breaks (it's a personal thing, i find that i can "slip" during pomodoro breaks, but if i have a time for like 3-5 hours i'd do my own breaks but always come back to work), it doesn't change much in program but it makes it much more universal.

**Comment by RoderickQiu** [comment]
Well, actually I've already written some of features that you mentioned, but may be I didn't write the hints in a clear way.
Disable notification sound: in the main window -> click the wnr icon -> go to settings -> global settings -> disable the section of "play sound to notify"
Disable additional window: go to settings -> global settings -> disable the sections "check after work time ends" and "check after rest time ends"
Arbitrary timer: in the main window -> click the wnr icon -> select "liberal timing" (if you don't want to be bothered in any circumstance, you should also disable the "nap setting“ section in settings panel)
As for the separate statistics feature, I won't implement it soon because I've been busy lately. But let's see if I will get some time to do it in late January.

**Comment by KEALHOVIK** [comment]
Hey, thanks for the quick answer. Yeah i use "liberal timing" too, but it not the same as ability to set a long timer without needing breaks.
I use liberal timing if i didn't plan to work or i plan to work just a little and i know i can be done with the task pretty quick. But i need a long timer without breaks to keep me working through the day. It can be used in that way as is. for now i just set a long timer with 1 break at 5 seconds at the end, but it's kinda annoying waiting for it to finish and go through popups and such.

**Comment by RoderickQiu** [comment]
Well, as a matter of fact, there is something called "just timing" that can be similar to your need of having a long while controllable working time (don't forget to disable the focus mode section).
But you know, as someone with Chinese as mother tongue, I cannot find how to give it a proper name to it... Maybe I should also re-think about the timing function modes' UX designing in my Jan update now...
