### ISSUE TITLE
The timer pauses when screen off or sign out (Windows)

### ISSUE THREAD

**Issue by 0xRR** [RoderickQiu/wnr#6]
Hi , I like this app but there is a thing bothering  me so much .
I went away for resting , the screen went dark , or the Windows Smart Lock detect my phone went away so he signen me out automatically . Then , after I had taken my resting and came back , sign in and found the timer still remain a lot so I have to wait it count down to zero .
That's really frustrated when using the fullscreen mode .

**Comment by RoderickQiu** [comment]
Thank you for using, also, thank you for not using Chinese and English instead so that everyone who visits this repo can get to know what current problems are and how we are going to solve them.

------
Currently, when the computer falls asleep, the timer stops. I'll have a selection for whether you want to have the timer still counting or not in the next release. 

Thanks for giving this suggestion. If you have another thing to say, feel free to write it down here.

**Comment by 0xRR** [comment]
It's really neat , thank you !

**Comment by RoderickQiu** [comment]
The new release v1.15.0 has been here, and you can download it and have a check.

If the problem presists, feel free to tell me to reopen this issue.

Thank you for this issue!
