### ISSUE TITLE
Task Reservation

### ISSUE THREAD

**Issue by EAZY5D** [RoderickQiu/wnr#64]
it'll be great to have the "task reservation" automatically get info from Online Calendars "Google Calendar" And add them to the tasks list automatically that would be a really great feature.

It'll be a one-way sync from google calendar to WNR.

**Comment by RoderickQiu** [comment]
Hello, sorry for the long delay caused by my Gaokao test preparation.
Anyway, as I myself doesn't use online calender providers' service and this feature doesn't seems like an easy one after researching, so I might not add this in recent versions. However, I will be happy to merge your pull request or provide any help I can if you want to add this feature yourself as a third-party contributor.
